webtalk_init -webtalk_dir C:/Users/hasan/Desktop/TOBB CS Hasan TUNA/21-22/SUMMER/BIL265/Project/Project_Final/Project_Final.sim/sim_1/behav/xsim/xsim.dir/tb_karekok_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Aug  5 16:36:55 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3daf5188-f595-4613-b3bb-58a9ea637f2c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c615fe0ecf6841fd825e8f982d1c00e1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "65" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7248_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1046732339 -regid "" -xml C:/Users/hasan/Desktop/TOBB CS Hasan TUNA/21-22/SUMMER/BIL265/Project/Project_Final/Project_Final.sim/sim_1/behav/xsim/xsim.dir/tb_karekok_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/hasan/Desktop/TOBB CS Hasan TUNA/21-22/SUMMER/BIL265/Project/Project_Final/Project_Final.sim/sim_1/behav/xsim/xsim.dir/tb_karekok_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/hasan/Desktop/TOBB CS Hasan TUNA/21-22/SUMMER/BIL265/Project/Project_Final/Project_Final.sim/sim_1/behav/xsim/xsim.dir/tb_karekok_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
